#! /bin/csh
#
#   make a tar file for "release"
#
#       Usage: mkrelease <version number>
#
#   Requires an argument for the version number
#   The "make clean" ensures that files like y.tab.c,
#   y.tab.h, etc are not put on the tar tape.
#
if( $#argv != 1 )then
	echo usage: $0 version
	exit 1
endif

cd ..
ln -s rnamotif rnamotif-$1
(cd rnamotif; make clean)
set tarfile = rnamotif-$1.tar
echo making $tarfile
tar cvXf rnamotif/excludes $tarfile \
	rnamotif-$1/README \
	rnamotif-$1/COPYING.GNU \
	rnamotif-$1/revision.history \
	rnamotif-$1/iupac.codes \
	rnamotif-$1/Makefile \
	rnamotif-$1/config.h* \
	rnamotif-$1/doc/rnamotif.pdf \
	rnamotif-$1/src \
	rnamotif-$1/efndata \
	rnamotif-$1/test
gzip -v $tarfile
rm rnamotif-$1
mv rnamotif-$1.tar.gz rnamotif
cd rnamotif
