#! /bin/csh
#   make a tar file for "release"
#   Requires an argument for the version number
#   The "make clean" ensures that files like y.tab.c,
#   y.tab.h, etc are not put on the tar tape.
#
if( $#argv != 1 )then
	echo usage: $0 version
	exit 1
endif
make clean
set tarfile = rnamotif-$1.tar
echo making $tarfile
tar cvf $tarfile \
	./INSTALL \
	./revision.history \
	./iupac.codes \
	./Makefile \
	./config.h* \
	./doc \
	./src \
	./efndata \
	./test \
	./descr
gzip -v $tarfile
